### ISSUE TITLE
Prevent connecting event-based gateway to event-based target when connection already exists

### ISSUE THREAD

**Issue by gustavjf** [bpmn-io/bpmn-js#1014]
__Describe the Bug__

It's currently allowed to connect an event-based gateway to an event-based target when a connection already exists between the two.

![bpmn-js#XXX](https://user-images.githubusercontent.com/3981598/57221869-fab53000-7000-11e9-91c0-a38e893604ec.gif)

__Steps to Reproduce__

1. Create an event-based gateway.
2. Attach an event-based target to the event-based gateway
   (ReceiveTask, IntermediateCatchEvent_Message, etc.)
3. Connect event-based gateway to newly attached target.

The existing connection is replaced with the new one.

__Expected Behavior__

The connection should be disallowed.

__Environment__

Please complete the following information:

 - Browser: Chrome 73
 - OS: macOS
 - Library version: bpmn-js@e4fe8c2, camunda-modeler@3.1.0

**Comment by barmac** [comment]
I'm not sure if we really want to disallow the connection. I might be wrong, but I think that so far we rather sticked to allowing the possibly not wanted behaviour as the user is always able to undo the action. For instance, we rather remove the existing connections in event based gateway behavior instead of forcing the user to remove the not allowed connections.

**Comment by gustavjf** [comment]
Wouldn't the change in connection ID be problematic? At the very least, I can see it causing some confusion apart from the fact that it's not immediately clear the old connection is replaced with a new one implicitly.

**Comment by nikku** [comment]
This is a severe problem and is better handled via linting, cf. [this comment](https://github.com/bpmn-io/bpmn-js/issues/935#issuecomment-529417523).
