### ISSUE TITLE
How to get source and target of element?

### ISSUE THREAD

**Issue by diegosliver** [bpmn-io/bpmn-js#1038]
I need to get the source and destination of an element that was selected with the mouse.

` eventBus.on(event, function(e) 
      {
        var elementRegister = this.modeler.get("elementRegistry");
`

I have used the elementRegistry, but it does not return this information I need.

After I click on a task for example, I need to know what element is before and after that task.

**Comment by pinussilvestrus** [comment]
Hi @diegosliver,

As I know, it isn't possible to get _all_ elements which are before / after one element directly. Each element has a _incoming_ and _outgoing_ property which includes the elements which are connected to it: 

```js
eventBus.on('element.click', function(e) {

var context = e.context,
    element = context.element;

// get incoming shapes
var incoming = element.incoming;

// get outgoing shapes
var outgoing = element.outgoing;

});
```

As you can see, you don't have to use the `elementRegistry`  for it, the element is exposed to the event itself. To get _all_ elements which come before and after, you will have to somehow loop through the `incoming` + `outgoing` properties. Just ask if you need more help.

Note: Feel welcome to use [our forum](https://forum.bpmn.io/latest) for questions. I'll close this since here is no bug or feature request described.

**Comment by diegosliver** [comment]
@pinussilvestrus Tanks!
