### ISSUE TITLE
How to hidden some item on left menu and replace menu?

### ISSUE THREAD

**Issue by hzyhbk** [bpmn-io/bpmn-js#1042]
__Is your feature request related to a problem? Please describe.__

- I want to hidden some item on left menu and 'replace menu', because there are too many elements on left menu  i don't use. And my server doesn't support all elements on left menu, the editor will be provided to many people who are not familiar with bpmn. if they add some elements that my server doesn't  support, the following processes will not continue. So I want to configure the left menu and 'replace menu' myself. But I only find the way to add  custom elements, so ...

__Describe the solution you'd like__

- I finally met my needs by modifying the source code in 
       '_bpmn-js/lib/features/palette/PaletteProvider.js_' ,
       '_bpmn-js/lib/features/context-pad/ContextPadProvider.js_' ,
       '_bpmn-js/lib/features/replace/ReaplceOptions.js_', 
I spent some time to find and annotate some options I don’t need. So could you provide me a way to deploy these options.

__Additional context__

**This is the original menu**

![left-menu](https://user-images.githubusercontent.com/42671099/58245093-9e833780-7d86-11e9-9477-7dc8cb763fd9.png)![replace-menu](https://user-images.githubusercontent.com/42671099/58245099-a3e08200-7d86-11e9-8a21-15688f79bc42.png)

**This is the revised menu**

![my-left-menu](https://user-images.githubusercontent.com/42671099/58245105-a6db7280-7d86-11e9-8dfc-37130253d21d.png)![my-replace-menu](https://user-images.githubusercontent.com/42671099/58245107-a8a53600-7d86-11e9-91ab-243d1748ad0f.png)

**Comment by pinussilvestrus** [comment]
Hi @hzyhbk ,

we have a couple of [examples](https://github.com/bpmn-io/bpmn-js-examples) which should help you to solve your problems. In this particular case, you can refer to our [custom controls example](https://github.com/bpmn-io/bpmn-js-example-custom-controls). 

Feel welcome to use our [forum for asking questions](https://forum.bpmn.io/latest). GitHub issues are intended to create bug reports and feature requests. There, you will also find [help for creating a custom `ReplaceMenuProvider`.](https://forum.bpmn.io/t/how-to-custom-menu-provider/2384/2)

I'll close this since no bug or feature request is described.
