### ISSUE TITLE
Cannot easily connect Task -> Task center anymore

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1086]
__Describe the Bug__

Given the introduction of connection previews and grid snapping there exists a couple of cases where we cannot connect two tasks center to center anymore. This is related to https://github.com/bpmn-io/bpmn-js/issues/1079, however the outcome may be different.

__Steps to Reproduce__

* Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/3300314/test.bpmn.txt)
* Try to connect the two tasks
* See how we are missing basic center -> center snapping and the interaction that results in

__Expected Behavior__

Center to center connection is the most common case (aka happy path) and should work without hazzles.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v4.0.0-beta.1

__Additional Context__

Old behavior (works): 

![bug-before](https://user-images.githubusercontent.com/58601/59662199-bf378500-91ac-11e9-82dc-a2e20af3acce.gif)

New behavior (does not work): 

![bug-after](https://user-images.githubusercontent.com/58601/59662218-c78fc000-91ac-11e9-96df-a9aa58acbed1.gif)

**Comment by pinussilvestrus** [comment]
I was indeed able to create a centric connection between two tasks:

![Jun-18-2019 11-26-47](https://user-images.githubusercontent.com/9433996/59670372-227ce380-91bc-11e9-9312-34da4f49d2f7.gif)

However, it makes sense to have it this per default, since as the screencast reveals, it does not snap on center in the first place.

Furthermore, there seems to be a bug with the connection adjustment when moving the centered connected tasks:

![Jun-18-2019 11-27-33](https://user-images.githubusercontent.com/9433996/59670520-607a0780-91bc-11e9-8f45-aca35afeec14.gif)

This might come from the same problem described here, but I'll create another issue for this.

**Comment by nikku** [comment]
@pinussilvestrus Please use the provided example diagram, too. It contains a not-yet-snapped process, the thing that is common, as diagrams are not generally snapped yet.

**Comment by pinussilvestrus** [comment]
Thanks for the hint! Yes, in this case, it is not possible to connect them center to center in any case.

**Comment by pinussilvestrus** [comment]
After a further discussion we will try out following way: When connecting Element -> Task

* Snap to target center if the cursor is in `center` of target
* Snap to grid position (as it is right now)

![taskSnapping](https://user-images.githubusercontent.com/9433996/59683010-a2647700-91d7-11e9-832f-74ade9fe18ae.png)

**Comment by pinussilvestrus** [comment]
Closed via 9b9ff934d2352ad082383c61adc069dc0ca0212d
