### ISSUE TITLE
Boundary Events not detached when moved out of host in a batch move

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1202]
![Screen Recording 2019-09-25 at 11 22 08](https://user-images.githubusercontent.com/28307541/65588246-77808080-df87-11e9-91e4-61ebe3fffb66.gif)

__Describe the Bug__

The Boundary Events are not converted to Intermediate Events when moved to canvas in a batch operation.

__Steps to Reproduce__

1. Select multiple Boundary Events
2. Move them to canvas.

__Expected Behavior__

Such operation should either be disallowed or the events should be converted to Intermediate Events.

__Environment__

 - Browser: Chrome
 - OS: MacOS
 - Library version: 5.0.4

**Comment by oguzeroglu** [comment]
[This line](https://github.com/bpmn-io/bpmn-js/blob/014359523071b86f885e87e4204f92686b55b3d6/lib/features/modeling/behavior/DetachEventBehavior.js#L34) causes the problem, since the array length is more than 1 in this case DetachEventBehavior just does an early return instead of replacing elements.

**Comment by oguzeroglu** [comment]
Replacing elements.move preExecute behaviour with this fixes the problem, however I'll apply these changes when #1203 gets merged to prevent conflicts in DetachEventBehavior

`  this.preExecute('elements.move', function(context) {
    var shapes = context.shapes;

    shapes.filter(function(shape) {
      var hasHost = (shape.host && (context.shapes.indexOf(shape.host) > -1)) ? true : !!context.newHost;
      return shouldReplace(shape, hasHost);
    }).map(function(shape) {
      return shapes.indexOf(shape);
    }).forEach(function(index) {
      shapes[ index ] = replaceShape(shapes[ index ], bpmnReplace);
    });
  }, true);`

This is the tricky part:

`      var hasHost = (shape.host && (context.shapes.indexOf(shape.host) > -1)) ? true : !!context.newHost;`

For edge cases where a boundary event is attached to a task and we move them all together, context.newHost is null however the Detach behaviour in that case should not apply to the Boundary Event (since it is being carried with its host), therefore we check if a shape has an host **and** this host is inside the moved shapes within the context.

**Comment by oguzeroglu** [comment]
Closed via #1206

**Comment by philippfromme** [comment]
Will be properly fixed through https://github.com/bpmn-io/bpmn-js/pull/1203
