### ISSUE TITLE
Properties Panel

### ISSUE THREAD

**Issue by mariohmol** [bpmn-io/bpmn-js#1228]
I'm looking for a properties panel to change the configuration for task , gateways and other elements.. as we have in Camunda Modeler.

Is this in the roadmap?

**Comment by pinussilvestrus** [comment]
The [`bpmn-js-properties-panel`](https://github.com/bpmn-io/bpmn-js-properties-panel) is built exactly for `bpmn-js` and is used in the Camunda Modeler. You can easily put this into your bpmn-js application. Just ask, if you need help in doing so.

I'll close this, since no real bug reported or feature request is included. You can use our [forum](https://forum.bpmn.io) to ask questions like that.
