### ISSUE TITLE
Label position got not adapted properly for boundaries

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js#1312]
__Describe the Bug__

When appending a new element from a boundary, its label position got not adapted properly

![Kapture 2020-04-17 at 11 41 14](https://user-images.githubusercontent.com/9433996/79555758-5f498d80-80a0-11ea-9990-138368655962.gif)

__Steps to Reproduce__

1. Model a boundary event on a subprocess (cf. screencast)
2. Append a new element
3. See the label didn't get moved to a better position

__Expected Behavior__

I would expect that the label got moved to another better fitting place, e.g. to the top or to the left

__Environment__

 - Browser: Chrome 80
 - OS: macOS 10.15
 - Library version: https://demo.bpmn.io/s/start

**Comment by philippfromme** [comment]
I'd not expect the label to overlap the subprocess instead of the sequence flow. The reason the label doesn't move is that there is no other position (top, right, left) where it wouldn't overlap another element.

For comparison:

![22-04-_2020_13-43-05](https://user-images.githubusercontent.com/7633572/79977919-5e00d200-849f-11ea-979b-ef12551eb628.gif)

**Comment by nikku** [comment]
I aggree with @philippfromme here and would like to close this as won't fix.

The particular scenario is not easy to solve and we explicitly decided to not make the label overlap with the host in the past (cannot find the reference, but we talked that through).

**Comment by pinussilvestrus** [comment]
I agree 👍
