### ISSUE TITLE
can i get a json data when i save my process

### ISSUE THREAD

**Issue by alphazhangyz** [bpmn-io/bpmn-js#1329]
can i get a json data like a tree when i try to save my process. the data contain root node，children node... every node has type,parent,child? such as 
{ 
 root: {
   type: ''
   name: '',
   children: [
      {
        type: '',
        name: '',
        children: [],
        parent: ''
      },
      {
        type: '',
        name: '',
        children: [],
        parent: ''
      },
    ]
  }
}

**Comment by pinussilvestrus** [comment]
1. Please make sure to [format your code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
2. Try to ask those questions inside [our forum](https://forum.bpmn.io/). GitHub issues are meant for feature requests and bug fixes.
3. This project does not offer what you're looking for out-of-the-box. We use [`bpmn-moddle`](https://github.com/bpmn-io/bpmn-moddle) to create a tree representation from the given XML internally. Maybe this could help you.

I'll close this issue since no feature request or bug report is given. Feel free to re-open if you have something like that.
