### ISSUE TITLE
'get' on proxy: property '$pkg' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')

### ISSUE THREAD

**Issue by jsliu27** [bpmn-io/bpmn-js#1433]
https://github.com/bpmn-io/bpmn-js-examples/issues/132#issue-859028921

**Comment by philippfromme** [comment]
When opening a [new issue](https://github.com/bpmn-io/bpmn-js/issues/new?assignees=&labels=bug&template=BUG_REPORT.md) there's a template for a reason and that is to avoid ending up with cryptic issues like this one. Please update the issue to adhere to this template. Otherwise, we won't be able to help you.
