### ISSUE TITLE
Pasting Multiple Shapes Onto Connection Results In Unexpected Connections

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1440]
__Describe the Bug__

![J8DRVppIr9](https://user-images.githubusercontent.com/7633572/116668611-de54ef80-a99d-11eb-9654-e34dae31b255.gif)

__Steps to Reproduce__

1. Copy two tasks
2. Paste the tasks onto a sequence flow

__Expected Behavior__

The [behavior](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/DropOnFlowBehavior.js) doesn't kick in for multiple shapes __or__ it connects them in a way that _makes sense_.

__Environment__

 - Library version: 8.3.1

**Comment by marstamm** [comment]
Root-Cause:

The elements are added in order from left to right, but on the same Sequenz flow. Because of that, the second element comes first, see the gif below:
![recording](https://user-images.githubusercontent.com/21984219/116685777-2f231300-a9b3-11eb-8002-e6320582cf2c.gif)

__Solution Ideas__
I see two options:
1. Add the Elements back-to-front.
2. Determine the target-Flow again after each element is created

However, both have Problems:
1. I have made a draft implementation in the linked diagram-js PR. However, reversing the order in which the elements are added in the `CreateElementsHandler` makes assumptions about the structure of the arguments hand feels like a hack.
2. The mouse event targets only one flow, so we do not have references to the next target flow. I'm not 100% sure if this approach can be achieve this without a bigger refactoring.

@philippfromme , I'd be interested in your opinion on this. Would changing the order when copying the shapes (opposed to when creating the new ones) make this less hacky?

**Comment by philippfromme** [comment]
Honestly, I think we should disable this behavior when more than one shape is created. We simply cannot know what connections to create if we are creating multiple shapes at a time. The behavior can also easily blow up completely:

![yX9DFnWuCq](https://user-images.githubusercontent.com/7633572/116692795-38b17880-a9bd-11eb-9844-4f6f2a957e50.gif)

**Comment by philippfromme** [comment]
Moving the elements is rejected so pasting should be rejected, too:

![O0Lj6CJnIq](https://user-images.githubusercontent.com/7633572/116693204-db69f700-a9bd-11eb-8ceb-559b793d1d18.gif)

**Comment by marstamm** [comment]
That sounds reasonable, I'll see if we can reuse logic from movement for pasting as well

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/b56604d5f350a12c9ab1175b5c1a2d36a79a3140
