### ISSUE TITLE
Moving elements onto breadcrumb blow up editor

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1511]
__Describe the Bug__

If I accidentally move an element over the newly introduced breadcrumbs the editor blows up:

![capture kZ2UqD_optimized](https://user-images.githubusercontent.com/58601/138278262-eb278440-7168-4c41-8a1a-176fe060f813.gif)

__Steps to Reproduce__

1. Drill down into [collapsed process](https://github.com/bpmn-io/bpmn-js/blob/develop/test/fixtures/bpmn/collapsed-sub-process.bpmn)
2. Move sub-process contents onto breadcrumb
3. __See editor blowing up (not recoverable)__

__Expected Behavior__

Two options: Move is rejected or, even better, breadcrumbs are ignored during dragging (`pointer-events: none`).

__Environment__

 - Browser: any
 - OS: any
 - Library version: bpmn-js@next (`develop`)

**Comment by nikku** [comment]
With #1506 closed we should give this another look, shall we @marstamm.

**Comment by marstamm** [comment]
I think this is a general problem with the viewer. You cannot move elements (on the breadcrumbs or otherwise). This https://github.com/bpmn-io/bpmn-js/blob/cd31ef4f02989e7ea2ea8f3977a25c6696875c72/lib/features/auto-resize/BpmnAutoResizeProvider.js#L36-L40 is the fix we need and it will be integrated with https://github.com/bpmn-io/bpmn-js/issues/1536

**Comment by nikku** [comment]
Note that we've solved it for the palette already; we shall aim for a similar fix, UI wise:

![capture G1p3qU_optimized](https://user-images.githubusercontent.com/58601/143213843-ac4834f8-ef7f-4e23-bf5f-2f3102246909.gif)
