### ISSUE TITLE
Direct editing in sub-process plane stays open after navigation

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#1609]
__Describe the Bug__

When I switch planes with direct editing active the editing box remains open (despite the element not being visible anymore).

![capture vuQ6Mm_optimized](https://user-images.githubusercontent.com/58601/155515880-d0f6feb4-6380-4c64-a709-7819926e17b4.gif)

__Steps to Reproduce__

1. Open [test diagram](https://github.com/bpmn-io/bpmn-js/files/8132113/direct-editing.bpmn.txt)
2. Direct edit inside plane
3. Switch to other plane
4. __See that direct editing remains open__

__Expected Behavior__

Direct editing is canceled on plane switch.

__Environment__

 - Browser: Chrome
 - OS: Linux
 - Library version: v9.0.1 (demo.bpmn.io)

**Comment by marstamm** [comment]
> Direct editing is canceled on plane switch.

I would go with a "submit" instead of a "cancel". It feels more intuitive when drilling down:
![Recording 2022-02-24 at 15 11 50](https://user-images.githubusercontent.com/21984219/155540196-e1818d0a-8af5-46cc-adc6-46411f9de4f5.gif)

vs. a cancel, where the Breadcrumbs show the ID instead:
![Recording 2022-02-24 at 15 10 13](https://user-images.githubusercontent.com/21984219/155540260-c61cc8b3-c2dd-4391-8e8a-958f1dff03c5.gif)
