### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by cmskit** [bpmn-io/bpmn-js#191]
To load/include bpmn-js as a external Composer-Package (https://getcomposer.org) into a PHP Web-App it would be great to add a composer.json to your Lib.

**Comment by nikku** [comment]
What project should the `composer.json` file be added in and how does the file relate to web-resources?

**Comment by cmskit** [comment]
If bpmn-js-seed is meant to be the "Distribution-Package" then it would be best to add composer.json to it. If a web-resource (like an CMS Plugin) is using Composer as package- and update-management, bpmn-js could be easily added as a requirement to the package. Then you only need to load the js-files from the right location (like vendor/bpmn-io/bpmn-js-seed/...).

**Comment by nikku** [comment]
Our prepackaged distribution package is [bower-bpmn-js](https://github.com/bpmn-io/bower-bpmn-js), feel free to fork it and add the `composer.json` to your fork.

We are not adding the file to our code base because it would be something we'd need to continuously support (and add quality assurance for).
