### ISSUE TITLE
event commandStack.elements.create.canExecute not raised

### ISSUE THREAD

**Issue by EhsanValiGeeksltd** [bpmn-io/bpmn-js#1942]
event `commandStack.elements.create.canExecute` never raised !
```

this.modeler = new BpmnModeler({ container: element});
this.eventBus = this.modeler.get("eventBus");
this.eventBus.on(["commandStack.elements.create.canExecute"]
, 999999, e =>
{
      console.log("event raised");
});
```

**Comment by nikku** [comment]
That is correct. What makes you assume that that event is raised? What would you like to accomplish?

**Comment by EhsanValiGeeksltd** [comment]
this event exists on the `eventBus ` and I want to cancel the event execution based on application rules. for example, I want to cancel participant creation by model, then open a dialog to create a participant

**Comment by nikku** [comment]
> this event exists on the eventBus 

I don't think so. You'll be otherwise able to catch it.

> I want to cancel participant creation by model, then open a dialog to create a participant

This is an interesting use-case. If you raise a concrete question (clearly outlining what you'd like to accomplish) on our [project forums](https://forum.bpmn.io/), then we may find a solution.

This issue tracker is for bugs and feature request only, however I see that you have usage related questions here.

**Comment by nikku** [comment]
They are fired, specifically when using the `create` tool:

![capture FsHJGj_optimized](https://github.com/bpmn-io/bpmn-js/assets/58601/16c486dd-daed-4af6-ae75-e6c71e371d31)

The way to customize creation is by hooking into our rules system. It uses `*.canExecute` events under the hood to determine (_before_ execution of an event) if the operation could be executed.
