### ISSUE TITLE
Hint users on where elements may be placed

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js#203]
We show a descriptive error message when ever a user tries to model something semantically broken.

Initial implementation (based on comments below):

* [x] only show drop-not-ok coloring, on root, too
* [x] display error message for drop flow node outside participant

**Comment by gimbel** [comment]
Here is another example where the user can be guided in a better way.

Given that a user tries to dram a connection from an event based gateway to an element that is not allowed (e.g. event gateway to service task).

Currently this is simply not possible, indicated by the red color.

Better: We display to the user, why this connection is not possible. E.g. by giving a hint.
"You are not allowed to draw this connection. Event based gateways can only be connected to receiving/catching events and receive tasks."

**Comment by gimbel** [comment]
I see some different options for guiding the user.

Situation:
Diagram already contains one pool + user tries to drag new element outside the pool

Then
1) we could simply reject it (would be default I guess)
2) we could reject it and show some advice in form of text ("Dear User, you cannot do this because you have to model a pool first...")
3) we could do a repair by also adding a pool around that new element (maybe also with some hint why we did so?)
4) anything else?

I'd go for option 3)
