### ISSUE TITLE
Allow Modeling Exclusive Gateways Without Marker

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2116]
### Is your feature request related to a problem? Please describe.

Since #2063 bpmn-js supports gateways without x marker.

The modeler should allow to remove the marker or add it if an existing model doesn't have it.

### Describe the solution you'd like

Add a toggle button to the "Change element" pop-up for exclusive data-based gateways, similar to the event non-/interrupting toggle.

The symbol should be an empty (none) gateway (i.e. without x-marker). The symbol is highlighted when the marker is missing from the gateway.

### Describe alternatives you've considered

Alternatively, the symbol could be a gateway symbol with x-marker that is highlighted when the marker is present in the actual gateway.

Second alternative: Don't add a toggle, but make "Exclusive Gateway (without marker)" an additional option in the "Change element" pop-up. Might be more confusing, but allows switching directly from non-exclusive gateways to an exclusive gateway without marker.

### Additional context

I'd like to make a contribution if the feature is accepted.

**Comment by nikku** [comment]
@sombrek Our goals include: Build modeling tooling that is simple enough, at the same time give least (irrelevant) choices to the users.

Looking at this request "marker or no marker" is a _style_ that should be applied automatically, consistently. Because of that we'll not accept any feature request that allows users to lead to build diagrams with an inconsistent style. I don't deem it important enough to add a UI switch.

What I support is two things:

* A [lint rule](https://github.com/bpmn-io/bpmnlint/tree/main/docs/rules) that ensures the marker is consistently set or unset on a diagram
* An automatic mechanism that either uses the marker (or not), depending on a static configuration (diagram editor) _or_ prior user preference (existing BPMN elements).
* Optional: A way to fix your diagram automatically.

There should be no real world use for a UI toggle "show or hide marker" per element.

**Comment by barmac** [comment]
Also notice that the specification discourages mixing X and non-X gateways in a diagram:

> A diagram SHOULD be consistent in the use of the “X” internal indicator. That is, a diagram SHOULD NOT
have some Gateways with an indicator and other Gateways without an indicator.
(page 289)

**Comment by barmac** [comment]
There is space for custom modules (e.g. "bpmn-js-no-marker-gateway") in the awesome-bpmn-io list: https://github.com/bpmn-io/awesome-bpmn-io?tab=readme-ov-file#bpmn-js
