### ISSUE TITLE
bpmn.io demo not working on IEx 11

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#295]
Reproduce:
- start demo.bpmn.io using IEx 11
- try modelling anything

Problem:
- it is basically impossible to model anything

Expected:
- IEx 11 works like Chrome

**Comment by cduicu** [comment]
What is the resolution ? Is there a commit/release that fixes it ? demo.bpmn.io still does not work with IE11 and I am having the same problems locally.

**Comment by ricardomatias** [comment]
It is fixed. We'll be updating demo.bpmn.io today.

[https://github.com/bpmn-io/diagram-js/commit/2a8027d51158c817e59671395051600be39bd2d4] - This was the commit that fixed part of the problem.

[https://github.com/bpmn-io/diagram-js-direct-editing/commit/0725bdc44dc01e38228c08255c8912c957fb694e] - The rest was fixed in this commit. So you have to update your `diagram-js-direct-editing` dependency in **bpmn.js** to fix it.

**Comment by cduicu** [comment]
Thanks, Ricardo! Are you going to create a patch release for bpmn.js to include this fix ? If not, when can I expect the next release ?

**Comment by ricardomatias** [comment]
We won't be releasing a patch release in bpmn-js. You can update your local diagram-js to the current master to fix this issue.

**Comment by nikku** [comment]
Updated our [demo app](http://demo.bpmn.io) with the IE 11 fix.
