### ISSUE TITLE
unsresolved reference <xsd:string>

### ISSUE THREAD

**Issue by linudaar** [bpmn-io/bpmn-js#330]
Hi, 
i am trying to open a BPMN file that contains a `property` with `itemSubjectRef="xsd:string"` in the bpmn.io online demo.
The process cannot be opend, it shows a message "Diagram may not render correctly due to import warnings. Show details" and the details show "unresolved reference <xsd:string>"

I reduced the xml to these essential lines:
```
  1 <?xml version="1.0"?>
  2 <definitions                                                                                                                                             
  3     xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" 
  4     xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"                                                                                              
  5     xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"                                                                                                    
  6     xmlns:di="http://www.omg.org/spec/DD/20100524/DI" 
  7     xmlns:xsd="http://www.w3.org/2001/XMLSchema"                                                                                                         
  8     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  9     id="_1439212904440" name=""  
 10     targetNamespace="http://sourceforge.net/bpmn/definitions/_1439212904440" 
 11     typeLanguage="http://www.w3.org/2001/XMLSchema" 
 12     >                            
 13   <process xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" id="PROCESS_1" name="">                                                                   
 14       <property xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" id="PROCESS_1_P_1" name="command" itemSubjectRef="xsd:string" />                                                                                                                                                                                   
 15   </process>
 16 </definitions>
```

Why is this and how do I fix it?
Thanks.

**Comment by nikku** [comment]
This is because `Process#itemSubjectRef` must reference a `tItemDefinition` which it does not.

**Comment by linudaar** [comment]
According to http://www.omg.org/spec/BPMN/20100501/Semantic.xsd `itemSubjectRef` is type `xsd:QName`

**Comment by nikku** [comment]
That is correct.

**Comment by linudaar** [comment]
So, `xsd:string` is a "qualified name", isn't it? thanks.

**Comment by nikku** [comment]
Yes, `xsd:string` is a qualified name with the namespace `xsd`. That does not help you though. The element referenced via the QName `xsd:string` simply does not exist.

In order to ensure the _semantic integrity_ of a BPMN diagram XSD schema compliance is not enough. 

To sheet some more light on this issue:

* The BPMN 2.0 standard uses QNames ([effectively ids](www.w3.org/2001/tag/doc/qnameids)) to reference elements with each other.
* The relationship between elements is not represented in the XSD schema but hidden behind QNames.
* You should look into [the meta-model](http://www.omg.org/spec/BPMN/20100501/BPMN20.cmof) or the specification document to learn about them.

This library does a lot of _semantic_ validation beyond schema level. In the process it detects if your diagram contains invalid references. It displays these problems _as warnings_ and attempts to open the diagram despite the issue(s).
