### ISSUE TITLE
If i add a pool everything else is forced to be part of a pool

### ISSUE THREAD

**Issue by elnin0815** [bpmn-io/bpmn-js#364]
If i add a pool i can't:

- move any objects outside of the pool
or
- add any new objects outside of the pool

sidenote: if i delete a pool every member of the pool deleted, i can't delete the pool whilst keeping its members

**Comment by gimbel** [comment]
This is inteded behaviour. 

Why? Because BPMN works that way. The standard says, that in a collaboration every flow node has to be inside a pool. 

If you do not have any pools, you are only modelling in the context of a process. Then it is ok. 

This actually makes a lot of sense from the perspective of the standard. 

Did you see our error message, which tries to point you to these facts?

**Comment by elnin0815** [comment]
This is not (completely) true, quote from the standard:

> A Collaboration can contain two (2) or more Pools (i.e., Participants). However, a Process that represents the work performed from the point of view of the modeler or the modeler’s organization can be considered “internal” and is NOT REQUIRED to be surrounded by the boundary of the Pool, while the other Pools in the Diagram MUST have their boundary (see Figure 9.5).

**Comment by nikku** [comment]
The current functionality is a solution for what we see as the most common case (_pool wraps elements_). I know there are a number of people out there that are big fans of the other case (_participants embedded into process diagrams_), too though.

Embedded participant modeling is not supported by bpmn-js as of yet because it imposes a number of interesting usability questions, such as how to distinguish it from the wrapping case.

One way to support this some time in the future would be to allow adding a participant (non-wrapping) via a _special key_. This is something most drawing tools support in order to create/move elements without snapping (or wrapping in this case).

Is this something that could address your issue? Any other idea how modeling interaction could support the creation of pools embedded in process diagrams?
