### ISSUE TITLE
I can move elements using the keyboard arrows

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#376]
Keyboard heavy users benefit from being able to move a selection of elements via keyboard.

__Tasks__

Adopting the default behavior from Adobe Illustrator:

* [ ] up/down/left/right moves the selected elements
* [ ] up/down/left/right + (CTRL/CMD) moves the canvas
* [ ] Move via reasonable amount per default
* [ ] Use the `SHIFT` modifier to move per pixel

**Comment by pinussilvestrus** [comment]
I think we should consider implementing it into the underlying https://github.com/bpmn-io/diagram-js keyboard-listeners

**Comment by barmac** [comment]
Moving the canvas is actually already implemented as key bindings to arrows via https://github.com/bpmn-io/diagram-js/commit/c77317bc831da9fae3f0236d49d8128829d9c479

The question is if it is reasonable to replace current bindings instead of leaving them as they are and adding `up/down/left/right + (CTRL/CMD)` to move elements. So the final bindings would be as follows:

- [x] up/down/left/right moves the canvas (already implemented)
- []  up/down/left/right + (CTRL/CMD) moves the selected elementsmoves the canvas
- []  Move via reasonable amount per default
- []  Use the SHIFT modifier to move per pixel

@philippfromme @nikku @pinussilvestrus What is your opinion?

**Comment by pinussilvestrus** [comment]
@barmac I'm totally with you! I would also prefer just adding a new keyboard listener for a new functionality instead of changing a working one to a new behavior. It would be very frustrating for active users when the current experience is changing.

**Comment by nikku** [comment]
I'd look into common practices for keyboard navigation rather than sticking to / preserving the status quo. 

* How are other graphical applications (Inkscape, Adobe *, Gimp, Word, PowerPoint, your local editing tool) doing it? 
* Does a common behavior exist? We should adopt it.
* No common behavior exists? We should think about this again.
* Do users need to be able to configure things? Make the behavior configurable. 
    (This may be introduced in future releases, too).

Our diagram-js release is already gonna be _breaking_ due to API changes we introduced. That means it is now is a good moment to clean up. Another aspect is the fact that keyboard shortcuts are not widely used (expert feature) and the improvement was proposed as an expert feature, by an expert.

**Comment by nikku** [comment]
Great research. Two comments:

* Moving Canvas and Elements with the keyboard (without a modifier) can be something very confusing for users; I suggest to user test this, once you got a prototype to try out; an alternative here is to use a modifier to move the canvas via arrow keys.
* Modifiers + Default move behavior: I like the idea of using the Keyboard to move elements with fine grained control. Need to try this out with users, too.

**Comment by barmac** [comment]
Sure, as soon as we have a prototype the final outcome might change. Thanks for comments 👍

**Comment by barmac** [comment]
Final default configuration will be as follows:

Shortcut | with selection | without selection
-- | -- | --
arrows | move elements per pixel | -
Shift + arrows | move elements per 10 pixels | -
Ctrl/Cmd + arrows | move canvas per 10 pixels | move canvas per 10 pixels 
Ctrl/Cmd + Shift + arrows | move canvas per 100 pixels | move canvas per 100 pixels

**Comment by barmac** [comment]
Closed via #887
