### ISSUE TITLE
A call activity is always shown with a "+" sign

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#403]
We need to update our [`BpmnRenderer`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/draw/BpmnRenderer.js) to always show the plus sign (__+__) for call activities.

The collapsed sub-process as shown below already has the marker (left). The call activity should get it, too.

![image](https://cloud.githubusercontent.com/assets/58601/11815220/1a83b220-a34b-11e5-9e5b-8bbf0b63ba30.png)

Test diagram for which that should work:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_1" isExecutable="false">
    <bpmn:subProcess id="SubProcess_02yxyt7" name="A" />
    <bpmn:callActivity id="CallActivity_1acw786" name="B" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="SubProcess_02yxyt7_di" bpmnElement="SubProcess_02yxyt7">
        <dc:Bounds x="245" y="130" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="CallActivity_1acw786_di" bpmnElement="CallActivity_1acw786">
        <dc:Bounds x="399" y="130" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by hoferch91** [comment]
Hey Robert,
I saw two possible adjustments to reach the required appearance:
1) extend the function belonging to 'bpmn:CallActivity'
2) delegate the rendering to the function of 'bpmn:SubProcess'

to 1): The return value of renderer('bpmn:Task')(p, element, ...) must be cached in a rect variable, afterwards call attachTaskMarkers(p, element, ['SubProcessMarker']) to add the (+)
to 2): function of 'bpmn:SubProcess' is called with the appropriate strokeWidth.

I chose the second solution, because:
- of consistency ( bpmn:AdHocSubProcess' and 'bpmn:CallActivity' call this function as well)
- no code duplication, less code

Best regards,
Chris
