### ISSUE TITLE
DataInputAssociation is missing targetRef

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js#431]
The schema mandates that a dataInputAssociation has exactly one `targetRef`:

```xml
<xsd:element name="dataAssociation" type="tDataAssociation" />
  <xsd:complexType name="tDataAssociation">
		<xsd:complexContent>
			<xsd:extension base="tBaseElement">
				<xsd:sequence>
					<xsd:element name="sourceRef" type="xsd:IDREF" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="targetRef" type="xsd:IDREF" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="transformation" type="tFormalExpression" minOccurs="0" maxOccurs="1"/>
					<xsd:element ref="assignment" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
```

However, the following XML is produced by the modeler:

```xml
<bpmn:userTask id="UserTask_0yn6r8j" name="Stuff!">
  <bpmn:dataInputAssociation id="DataInputAssociation_0gjpa46">
    <bpmn:sourceRef>DataObjectReference_1uyam7f</bpmn:sourceRef>
  </bpmn:dataInputAssociation>
</bpmn:userTask>
```

**Comment by nikku** [comment]
The Camunda Eclipse Plug-in does this wrong, too.

**Comment by nikku** [comment]
We need to generate input/output specification and friends boilerplate properly in order to support DataAssociations in a BPMN 2.0 compliant way.

From the [BPMN 2.0 Spec formal PDF document](http://www.omg.org/spec/BPMN/2.0/PDF), page 34:

> Data Association is ABSTRACT: Data Input Association and Data Output Association will appear in the XML serialization. These both have REQUIRED attributes[sourceRef and targetRef] which refer to itemAwareElements. To be consistent with the metamodel, this will require the following additional elements:
ioSpecification, inputSet, outputSet, Data Input, Data Output. When a BPMN editor draws a DataAssociation to an Activity or Event it should generate this supporting invisible substructure. Otherwise, the metamodel would have to be changed to make sourceRef and targetRef optional or allow reference to non-itemAwareElements, e.g., Activity and Event.

**Comment by berndruecker** [comment]
Is this already contained in the current Camunda Modeler Nightly? I still can reproduce the bug there.

**Comment by nikku** [comment]
Not yet in the nightly.
