### ISSUE TITLE
Mobile click on elements not always working 

### ISSUE THREAD

**Issue by filipe202** [bpmn-io/bpmn-js#449]
When I'm using bpmn.io in a mobile browser, clicking in an element doesn't always open the context pad.
I reproduced the problem in the demo provided in google chrome using the emulator.
What's not working?

**Comment by zhuangxiaohui** [comment]
Hello, when can you fix this problem？

**Comment by nikku** [comment]
We are open to contributions that improve our mobile support.

**Comment by zhuangxiaohui** [comment]
My English is poor, please forgive the following translation software, may be a little weird

I found this js problem:
https://github.com/bpmn-io/diagram-js/blob/master/lib/features/touch/TouchInteractionEvents.js

On mobile, [click] will have 200~300 ms, so please use [tap] instead of [click] as the click event

Method 1: fastclick

A library called fastclick making, it also can avoid delay response of the click event on a mobile device, [https://github.com/ftlabs/fastclick](https://github.com/ftlabs/fastclick)
Or you can refer to this

Method 2: bind the touchend event for the element, and add` e.preventDefault(); `
`$demo.on('touchend',function(e){
    $demo.hide()
    e.preventDefault();
})
`
I still know how to modify this problem, hope it is helpful to you

**Comment by vcartelli** [comment]
Just comment out 'click' and 'dblclick' in TouchInteractionEvents.js:
`var mouseEvents = [
  'mousedown',
  'mouseup',
  'mouseover',
  'mouseout',
  // 'click',
  // 'dblclick'
];`

**Comment by nikku** [comment]
@vcartelli Does that fix or substantially improve the mobile support? And if so, why? 

If that is the case you could file a PR and we see if we can get this thing merged.

**Comment by nikku** [comment]
The recent [`bpmn-js@8.9`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#890) release ships with improved touch support. Please give it a try and report back.

**Comment by aman123424** [comment]
@nikku , is this issue resolved, if not then I would like to contribute to this

**Comment by prachiMeshram** [comment]
@nikku is this issue resolved?
If not I would like to go ahead with it.

**Comment by nikku** [comment]
Happy to take contributions that improve our mobile support.

**Comment by nikku** [comment]
This issue is not resolved yet. Otherwise it would be closed.

**Comment by nikku** [comment]
Closing this issue. We completely removed the broken touch support with [`v17.0.0`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1700).
