### ISSUE TITLE
Resizing the block to fit the contents

### ISSUE THREAD

**Issue by mhariri** [bpmn-io/bpmn-js#450]
can the block resize to fit the contents if there is a lot of text in the block?

![screen shot 2016-01-19 at 15 16 12](https://cloud.githubusercontent.com/assets/1328129/12420935/bf192e52-bebf-11e5-8dbb-e2c14bd80758.png)

**Comment by nilei** [comment]
Hi Mohsen,

I think the activities should all have the same size as otherwise, bigger activities would read like being more important.
Instead you should consider to use documentation or -if unavoidable- text annotations.

Best practice is to use "noun verb" notation which usually is "shrinkable" to only some good descriptive words with no loss of information but not that verbose.

:-)

-- Cheers, Nils

**Comment by nikku** [comment]
Agreed to @nilei. If you would like your custom modeler that allows resizing of tasks, build it.

Checkout [bpmn-js-nyan](https://github.com/nikku/bpmn-js-nyan) for an example that does this.

**Comment by mhariri** [comment]
OK, thanks for the quick feedback :)
