### ISSUE TITLE
Modeler exception for model /taskAssignmentEmail.bpmn

### ISSUE THREAD

**Issue by leolux** [bpmn-io/bpmn-js#456]
When you open the model https://github.com/camunda/camunda-bpm-examples/blob/master/usertask/task-assignment-email/src/main/resources/taskAssignmentEmail.bpmn the following exception occurs:

> Unexpected close tag
> Line: 824
> Column: 7
> Char: >

**Comment by nikku** [comment]
Did you inspect the file to see what is up at __line 824, column 7__?

Because it looks like you tried to open the Github HTML page embedding the file instead of the actual [bpmn diagram](https://raw.githubusercontent.com/camunda/camunda-bpm-examples/master/usertask/task-assignment-email/src/main/resources/taskAssignmentEmail.bpmn).

**Comment by leolux** [comment]
You are right. I forgot to click the "raw" button :(

Thanks!
