### ISSUE TITLE
Camunda modeler: Unable to open files from examples

### ISSUE THREAD

**Issue by pradysam1** [bpmn-io/bpmn-js#485]
The camunda modeler cannot open files located in the examples directory

**Comment by nikku** [comment]
Please be more specific:

* What did you try (reproducible steps)?
* What was the expected behavior?
* What happened (error messages / other _wrong_ things)?

Do you talk about the [Camunda Modeler](https://github.com/camunda/camunda-modeler)? Open a ticket in its [issue tracker](https://github.com/camunda/camunda-modeler/issues) then.
