### ISSUE TITLE
Empty line at the end of description didn't vanish after deletion

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmn-js#763]
I add a newline at the end of a task name.

![grafik](https://user-images.githubusercontent.com/7870843/35919338-0e6dbba4-0c15-11e8-8eb4-13e5321d0743.png)

Then I delete the the empty line.

### Expected Behavior
The task name is in the middle of the task

### Actual Behavior
The task name is shift to the top

![grafik](https://user-images.githubusercontent.com/7870843/35919371-2a0ba2f4-0c15-11e8-8478-17015d131d0c.png)

### Steps to reproduce the Behavior

1. Add a newline with shift+enter at the end of a task name.
2. Click to the next task. 
3. Delete the empty line

**Comment by nikku** [comment]
I can confirm this bug. Thanks for the report.

**Comment by gustavjf** [comment]
I think this might be a bug in diagram-js instead of bpmn-js.

Two newlines are inserted when pressing shift+enter in a contenteditable div, which are later [parsed](https://github.com/bpmn-io/diagram-js/blob/914441b154739c9df27039f93da53dfd096f14b3/lib/util/Text.js#L334) as `<tspan>` tags when pressing enter.

Before pressing enter:
![bpmnjs-screenshot_02](https://user-images.githubusercontent.com/3981598/51319080-61b3d680-1a5c-11e9-97cc-9c5c8a298087.jpg)

After pressing enter:
![bpmnjs_screenshot_04](https://user-images.githubusercontent.com/3981598/51319329-0209fb00-1a5d-11e9-8235-5ccfb314be01.jpg)

Once those two characters have been inserted and the task is rendered as SVG after pressing enter, only one is removed on backspace when trying to edit again. This leaves a stray `<tspan>` in place, causing the unwanted space.

![bpmnjs-screenshot_03](https://user-images.githubusercontent.com/3981598/51319363-1c43d900-1a5d-11e9-9a22-3b5d87317466.jpg)

I thought of trimming whitespace before parsing as `<tspan>` tags [here](https://github.com/bpmn-io/diagram-js/blob/914441b154739c9df27039f93da53dfd096f14b3/lib/util/Text.js#L265) but I noticed two things:

1. A user will not see the rendered effect of inserting newlines without any text following it. This may or may not be desirable.

2. The text content of the contenteditable div and the result of the rendered SVG will not be in sync. The rendered SVG will not have trailing `<tspan>`s but the contenteditable div will retain the newline characters when going back to edit.

For what it's worth, trimming and thus preventing trailing whitespace from being rendered as SVG would also prevent the task's text from being rendered outside of the task itself:

![bpmnjs-screenshot_01](https://user-images.githubusercontent.com/3981598/51319701-10a4e200-1a5e-11e9-9827-7dc8bf323688.jpg)

Any thoughts? If the two points above aren't an issue, I could prepare a PR with the trim I mentioned.

**Comment by nikku** [comment]
My guess is that we must properly handle this issue in [diagram-js-direct-editing](https://github.com/bpmn-io/diagram-js-direct-editing). 

One approach would be to make sure that the text is trimmed after editing, committing it without trailing and leading whitespace.

**Comment by gustavjf** [comment]
Makes sense, how about [this](https://github.com/bpmn-io/diagram-js-direct-editing/pull/10)?

**Comment by nikku** [comment]
Needs patch release of diagram-js.

**Comment by gustavjf** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js/commit/0cfd960cdd45a0b3036df1495bffd35c7fb32a79
