### ISSUE TITLE
Auto-scrolling makes use of element palette difficult

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js#770]
- When
  - I've select an item from the palette and want to select a new item
- Then
  - The auto-scrolling feature is triggered as soon I hover over the palette
- A nicer behaviour would be:
  - As long I hover over the palette the auto scrolling is not active

![auto_scrolling](https://user-images.githubusercontent.com/2777965/34991318-7787ff6c-fac9-11e7-8996-ac31171a06c9.gif)

**Note**: Discussed with @nikku

**Comment by philippfromme** [comment]
A more general question would be if we want auto-scrolling at all. Currently auto-scrolling is active whenever a dragging operation is active (e.g. hand tool, lasso tool, space tool, creating an element from the palette). This particular issue does not exist in the [bpmn.io demo](https://demo.bpmn.io/s/start), since the palette is positioned differently (red border is canvas, blue border is palette).

### demo.bpmn.io:

<img width="618" alt="demo" src="https://user-images.githubusercontent.com/7633572/37590432-9390f11c-2b68-11e8-9714-437b82327ac1.PNG">

### Cawemo:

<img width="462" alt="cawemo" src="https://user-images.githubusercontent.com/7633572/37590441-9a51e344-2b68-11e8-8b89-419737a8c5a0.PNG">

**Comment by CatalinaMoisuc** [comment]
An example in [bpmn.io demo](https://demo.bpmn.io/s/start)
![bpmn-io-demo_auto-scroll](https://user-images.githubusercontent.com/25924333/37653205-55a37088-2c3e-11e8-86b4-feccd8fd6a24.gif)

**Comment by philippfromme** [comment]
This is the expected behavior in the demo.

The difference is that the area for auto-scrolling doesn't overlap the palette (outside of the palette auto-scrolling is okay)

I've colored the area for auto-scrolling in green.

### demo.bpmn.io

![element 1](https://user-images.githubusercontent.com/7633572/37890256-2945b258-30d0-11e8-8100-f91ceeefb9f8.png)

### Cawemo

![element 1](https://user-images.githubusercontent.com/7633572/37890287-4dd36192-30d0-11e8-9613-04648108f5b5.png)
