### ISSUE TITLE
I lose my content when I collapse the pool and expand it again

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/bpmn-js#775]
![collapse_expand_pool_lost_my_diagram](https://user-images.githubusercontent.com/25924333/38085903-a90713cc-3352-11e8-9cb0-b5dcf8ea3de9.gif)
**Question**: also, is the collapsed pool ment to look almost the same when collapsed?

**Comment by philippfromme** [comment]
This the expected behavior. In contrast to collapsed subprocesses which are only collapsed visually a collapsed participant means that there is another process that we don't own so instead of its inner workings we only know the interface for example. Therefore it makes no sense to keep the participants children when changing it to a collapsed participant. You can still undo the change to go back to the expanded participant.

To answer your question: Yes, this is how collapsed participants are supposed to look.

**Comment by nikku** [comment]
As @philippfromme indicated there is no easy way around this.

We've opened a feature request a while ago to preserve the contents, despite BPMN 2.0 limitations: https://github.com/bpmn-io/bpmn-js/issues/736.
