### ISSUE TITLE
Modeler problem and Right-To-Left Pages

### ISSUE THREAD

**Issue by MehdyKarimpour** [bpmn-io/bpmn-js#839]
### Expected Behavior
Modeler should works like Left-To-Right pages.

### Actual Behavior
The margin of the modeler will corrupt and you will have not the auto-popup menu when you select an element. I mean the popup menu use for creating upcoming elements like Gateway, Activity, Event and etc.

### Steps to reproduce the Behavior
1- Open Firefox and then go to demo.bpmn.io then press Create link.
2- Make a simple model like Start -> Activity -> End.
3. Right-click on the page and select "Switch Page Direction".
4. The margin of the modeler will corrupt and you will have not the auto-popup menu when you select an element. I mean the popup menu use for creating upcoming elements like Gateways, Activities, Flows, Events and etc. (Look at below image, the horizontal scroll of the page and the activity is selected but there is no popup menu)

![image](https://user-images.githubusercontent.com/6736338/43206304-9f0dc182-903a-11e8-8750-b77f6b2a7b4a.png)

**Comment by nikku** [comment]
Could you elaborate on this right-to-left mode? What is it for? Under which circumstances is it automatically _on_?

**Comment by nikku** [comment]
We'd be happy to take contributions that help us improve the support on right-to-left pages.

**Comment by MehdyKarimpour** [comment]
Hi nikku,
Thanks for your reply and sorry for delays.
The Right-To-Left pages use for those countries that have Right-To-Left languages like Arabic, Thai, Hebrew, etc...
So, I do not know what do you want exactly to know about RTL, actually I think it is obvious.
Would you please explain more what you need to support RTL?

best regards,
mehdy

**Comment by nikku** [comment]
I'd appreciate some insights how RTL influences element styling.

**Comment by nikku** [comment]
We'd be grateful if you could help us improve the support for RTL languages.

**Comment by MehdyKarimpour** [comment]
For the modeler, RTL means:
1- Palette should align to Right.
2- Powered by bpmn.io logo should align to Left.
3- When you select an element, the quick popup menu should appears on Left.
4- Vertical scrollbar should align to Left.

Something like mirroring.

best regards,
mehdy

**Comment by 1994samaneh** [comment]
Hello,

I am going to write rtl text inside text element, while it have to show the text in right direction, the result is like below:

Here in ltr direction, text position is true but the problem is text direction,
![screenshot from 2018-12-14 18-03-36](https://user-images.githubusercontent.com/42494888/50009044-2a6c8880-ffcb-11e8-9534-2cf773a150a9.png)

The time we change direction into rtl, text is showing in an wrong position,

![screenshot from 2018-12-14 18-04-45](https://user-images.githubusercontent.com/42494888/50009155-82a38a80-ffcb-11e8-999f-d903f9bac150.png)


More info about rtl in svg:
https://www.w3.org/International/tutorials/svg-tiny-bidi/
