### ISSUE TITLE
How to make the SVG pictures generated by bpmn.js read-only？

### ISSUE THREAD

**Issue by Super-Mumoo** [bpmn-io/bpmn-js#949]
let the user can only see and drag the whole picture,but cannot do other operation.

**Comment by nikku** [comment]
Could you be more precise about the thing you'd like to achieve?

We offer a Modeler and a Viewer distribution. The viewer is meant to be the read-only view you describe.

**Comment by Super-Mumoo** [comment]
emmmmm
![image](https://user-images.githubusercontent.com/38457677/54666289-56e0f500-4b24-11e9-8026-c10ca02a60f8.png)

**Comment by pinussilvestrus** [comment]
So you will need to use the [`Viewer`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/Viewer.js) instead of the Modeler. Have a look inside the [starter example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/starter) on how to use it 🙂 

Since there does not seem a real bug report or feature request, I'll close this issue. Feel free to re-open it if so 👍 

Note: Feel free to [use our forum](https://forum.bpmn.io/) if you have questions. The GitHub issues are meant for bug reports and feature requests in the first place.

**Comment by nikku** [comment]
If you'd like to support dragging the canvas, choose the [`NavigatedViewer`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/NavigatedViewer.js).

**Comment by Super-Mumoo** [comment]
My current solution is '$('svg *').css({ "pointer-events": "none", "cursor": "default" });', but I dont think its a good solution,That's why I asked.thanks for ur work.
